### ISSUE TITLE
LED doesn't work with OnlyKey Original on BETA-8

### ISSUE THREAD

**Issue by yaDMdivaD** [trustcrypto/OnlyKey-Firmware#104]
I have 3 OnlyKeys now and love them.  I use my original only key to let friends test it out before they buy their own.  I recently attempted to put beta-8 on the original and while it does work, the LED now does not work. 

Is there a fix for this or will a new version of beta-8 be released just for the original?

**Comment by onlykey** [comment]
@yaDMdivaD We discontinued the original back in 2016, we continued to support it for up to beta7 but that was the last release supporting the original.

**Comment by yaDMdivaD** [comment]
I kind of assumed that but wasn't sure cause i saw the original referenced in the source code for 8.  No worries. Thank you for the quick reply.
