### ISSUE TITLE
OnlyKey does not work with AWS IAM U2F

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [trustcrypto/OnlyKey-Firmware#106]
Using firmware v0.2-beta.8c, I get no response from AWS IAM U2F. I am unable to register the OnlyKey as a U2F device. No blue flashing light, not response from the web app.

Not sure how to debug. I can give you more info if you tell me how.

OnlyKey Firmware v0.2-beta.8c
OnlyKey App v5.2.0
Acer Aspire 5 laptop
Ubuntu 18.04.1
Linux Kernel 5.0.0-37-generic
Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by jamesvl** [comment]
I've been using my OnlyKey successfully as an AWS IAM U2F for quite a while now, without issue.

I'm also on Linux (Fedora 31) and firmware beta.8c. (ThinkPad laptop though.) No issues with either FF or Chrome.

I take it your key works on other U2F sites?
