### ISSUE TITLE
[Question/Feature Request] Authy support

### ISSUE THREAD

**Issue by TheRobLP** [trustcrypto/OnlyKey-Firmware#109]
Hello, does OnlyKey work with the authentication app "Authy" ? If not, can you please add support for it in the future, if possible?

**Comment by onlykey** [comment]
@TheRobLP Not really sure what a security key working with Authy would look like. Both OnlyKey and Authy can generate TOTP codes, so you could store your account in both Authy and OnlyKey if that is what you are looking for.
