### ISSUE TITLE
Cannot wipe an OnlyKey on Windows 10

### ISSUE THREAD

**Issue by M-Pixel** [trustcrypto/OnlyKey-Firmware#113]
Since Firmware 8 changed the method of loading firmware to address the Windows 10 security changes, there doesn't seem to be any way of resetting an OnlyKey.

I have an OnlyKey whose PIN I've forgotten, so I need to reset it.  The OnlyKey app doesn't allow me to do anything, including loading firmware, because "Your OnlyKey is locked".  So it seems I need to load an older version of the firmware with Teensy Loader in order to wipe it.  Unfortunately, Teensy Loader can't communicate with the OnlyKey (I suspect this is due to the same Win10 security improvements that caused the need to upgrade firmware differently since Beta 8).  So there's no option for me except to install a different operating system to a spare computer.

**Comment by onlykey** [comment]
@M-Pixel You don't need the app to reset it, entering 10 incorrect PIN attempts will do it.
