### ISSUE TITLE
Keyboard LAYOUT_DANISH_MAC

### ISSUE THREAD

**Issue by Tobshobs** [trustcrypto/OnlyKey-Firmware#114]
I have made the layout for Danish Mac Keyboards.

It is not tested directly from the Onlykey.

How shall I proceed? Shall I make a pull request as is?

**Comment by onlykey** [comment]
@Tobshobs Yes that would be great! Thanks.

**Comment by Tobshobs** [comment]
For reference:
https://github.com/trustcrypto/OnlyKey-Firmware/pull/115
