### ISSUE TITLE
Unable to upgrade Firmware

### ISSUE THREAD

**Issue by george-151** [trustcrypto/OnlyKey-Firmware#116]
I have the multi color led onlykey (firmware 0.2 – beta.7c), windows 8.1
I can’t upgrade to 0.2 – beta.8c
When I try to upgrade, i get a steady white light.
I have successfully upgraded to 0.2 - beta.8c.hex (debug version) with teensy.exe
Please, provide the firmware (0.2 – beta.8c) in a hex format

**Comment by onlykey** [comment]
@george-151 If you have old firmware you may have to run the OnlyKey app as admin to upgrade on Windows.
