### ISSUE TITLE
OpenSSH ed25519-sk keys support

### ISSUE THREAD

**Issue by Kagami** [trustcrypto/OnlyKey-Firmware#123]
Hi, sorry if I chose the wrong OnlyKey's project to file this issue to.

According to https://docs.crp.to/openssh.html

> The OnlyKey currently only supports ecdsa keys with OpenSSH.

Is it possible to support ed25519-sk FIDO keys with OpenSSH too?

As far as I understand from [fido2/crypto.cpp](https://github.com/trustcrypto/libraries/blob/0dc7cf0fa7734d342759b4dd83706248b0eb8640/fido2/crypto.cpp), there is support for 25519 curve in OnlyKey's FIDO2 implementation. Is there some OpenSSH-specific issue which prevents using ed25519-sk with OnlyKey?

Please help me understand. Thanks.

**Comment by onlykey** [comment]
@Kagami Yes this is supported with the latest v2.1.1 firmware. We just have not updated the documentation yet here https://docs.crp.to/openssh.html feel free to use ed25519-sk with OnlyKey firmware v2.1.1.
