### ISSUE TITLE
HMAC does not work after FW upgrade with KeePassXC

### ISSUE THREAD

**Issue by pinkavaj** [trustcrypto/OnlyKey-Firmware#124]
Upgrade from v0.2-beta.8c
Upgrade to: latest firmware (v2.1.1-prodc)
KeePassXC version: 2.6.6

Steps to reproduce:
* Setup OnlyKey in HMAC mode to authenticate to KeePassXC
* Login to KeePassXC works
* Backup OnlyKey
* Upgrade FW using the app
* Restore configuration from backup
* Login to KeePassXC does not work any more
* Just downgrade the FW to older version allows KeePassXC authentication again

Other functions I use seems working (TOTP etc)

**Comment by onlykey** [comment]
Yes, we had an announcement for this in the upgrade guide until recently. You will need to follow this guide. https://docs.crp.to/keepassxc-upgrade.html

**Comment by pinkavaj** [comment]
Thx, this solved the issue for me.
