### ISSUE TITLE
Lock Pin & SD Pin can be the same

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-Firmware#13]
Add check so Lock Pin and SD Pin can't be the same. Also PD pin would need this check as well.

**Comment by onlykey** [comment]
I don't think we will be able to address this one. TODO add to release notes and documentation. Don't set the same PIN for both, if you do SD PIN will not work.

**Comment by onlykey** [comment]
Note has been added to quick start guide
