### ISSUE TITLE
No LED activity on STD Color /w latest FW

### ISSUE THREAD

**Issue by chriseomi** [trustcrypto/OnlyKey-Firmware#130]
I upgraded one of my spare STD Color OKs to latest firmware (OnlyKey v2.1.1-prodc). This was via the Teensy method first to get to `OnlyKey_Beta7_STD_Color.cpp.hex` then inapp to get to latest.

However it seems there is no LED activity at all. Not when I plug in type or anything. I changed brightness in the settings from default to 10, but that didn't help. TBH not sure what the LED status was before the upgrade, but wondered if I did anything wrong? Maybe its a HW fault?

**Comment by onlykey** [comment]
Can you try plugging into a USB hub? Early hardware models ~2017 had an LED that had issues on some systems where the USB voltage is higher than spec.
