### ISSUE TITLE
Explain the changing sha256sum on the github release page. WTF!?

### ISSUE THREAD

**Issue by vwas2** [trustcrypto/OnlyKey-Firmware#133]
i goto https://github.com/trustcrypto/OnlyKey-Firmware/releases and downloaded latest, do local checksum all good.
![image](https://user-images.githubusercontent.com/52429424/147797480-e01ed75c-c723-42c4-9c53-f8cb48bd73c8.png)

Until i checked the google cache for the same release (cache snapshot is  22. Dez. 2021 14:24:35 GMT ) **and the checksums seem to have changed!**. Dear trustcrypto or even github you have explaining todo!
![image](https://user-images.githubusercontent.com/52429424/147797530-19fa657a-4a4f-4ab0-a34c-8bd22a4c6516.png)

**Comment by onlykey** [comment]
As the firmware was marked as pre-release and a potential issue was identified by a user with the touch sense the firmware release was updated with the fix
