### ISSUE TITLE
OnlyKey doesn't seem to work with Ebay

### ISSUE THREAD

**Issue by SkyKwas** [trustcrypto/OnlyKey-Firmware#144]
I currently use OnlyKey as a security key for several online accounts including Google, GitHub, etc. But I can't seem to get it to work with Ebay.

I mainly use LibreWolf with some extensions on Linux Mint and have had no problems linking my key to other accounts. I've also tried Chromium, but the option to add a key doesn't even show up in Ebay.

I'm slowly maximizing the security of all my online accounts one by one since I'm using KeePassXC and OnlyKey. I don't know if this is something on Ebay's side or LibreWolf or something else, I was just hoping to have all my account accessible from one browser.

I don't know if I'll run into another issue like this as I'm going down my list of accounts, I just wanted to post this asking if there is a known issue with specific online accounts that have the option to add a hardware key. I'm curious why it doesn't work knowing that the OnlyKey is FIDO2 certified.

**Comment by onlykey** [comment]
Have you tried any other FIDO security keys on the setup such as Yubikey? If that doesn't work either then its probably something with the browser your using. I just checked and Ebay works fine for me with Chrome on Mac.

**Comment by SkyKwas** [comment]
Unfortanetly, I don't have a Yubikey. It's most likely my browser or one of my addons like uBlocko blocking something. Now that I know it _can_ work (it works for you), I'll keep trying different things to get it to work.

I'll give an update if I can figure it out. Thank you.

**Comment by SkyKwas** [comment]
I think I should close this issue as incomplete. I'm sure it's because of my setup, but I want to keep it the way I have it. If I find a solution, I'll try to remember to put it here. If someone reading this has a solution, can you please comment what you did to get it working?

My setup includes:
>Linux Mint 20.3 v5.2.7
LibreWolf Browser v101.0.1-1
OnlyKey App v5.3.4
OnlyKey Firmware v2.1.2-prodc
