### ISSUE TITLE
Support OnlyKey connection to iPhone through Lightning to USB-C OTG Adapter

### ISSUE THREAD

**Issue by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [trustcrypto/OnlyKey-Firmware#159]
I purchased a Lighting to USB-C OTG Adapter here: https://onlykey.io/collections/accessories-1/products/mcdodo-type-c-to-lightning-otg-adapter-pd-fast-charging-connector-for-iphone-11-12-13-14-pro-max-xs-xr-3a-charger-data-converter

And connect OnlyKey DUO to its USB-C port, then connect them to the iPhone's Lighting port. It doesn't work. 

There's no color flashing on OnlyKey DUO. Please support it.

**Comment by onlykey** [comment]
Do you have another adapter you could try? This should work on iPhone, it may be a faulty adapter.

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
> Do you have another adapter you could try? This should work on iPhone, it may be a faulty adapter.

No. I only bought 1 adapter and it works when it comes to charging.

**Comment by gibsonjareds** [comment]
I successfully used this adapter with the Duo after removing it from the USB-C sheath:

https://onlykey.io/collections/all/products/jh-link-new-2-in-1-type-c-lightning-usb-otg-adapter-3-1-data-transfer-for-mobile-phone?variant=41949487202490

However, the fit was so tight, that the force needed to push it in all the way caused the buttons on the device to break on a subsequent attempt:

https://onlykey.discourse.group/t/onlykey-duo-buttons-broke-when-using-adapter/1003/2

So I’d recommend exercising caution if you try it.
