### ISSUE TITLE
Unlocking OnlyKey PIN using terminal

### ISSUE THREAD

**Issue by mihakrumpestar** [trustcrypto/OnlyKey-Firmware#175]
After reading all the docs I can't find any way to unlock OnlyKey PIN from the terminal. This apparently works for YubiKeys.

For example:

- Tested: `pamu2fcfg` just waits if OnlyKey is locked, Yubikey apparently prompts for PIN
- Untested: unlocking LUKS encrypted partitions not possible without unlocking the key physically (eg. with onboard buttons), Yubikey apparently prompts for PIN

The OnlyKey CLI also does not have any way to unlock the key (to enter the PIN).

**Comment by onlykey** [comment]
OnlyKey PIN is entered on the device itself and cannot be done from the terminal.

**Comment by mihakrumpestar** [comment]
I do understand that the entering on the device might be preferred by some, but it is much faster to type in the terminal. OnlyKey App is capable of unlocking the device, so it should be possible to do the same from the terminal.

**Comment by onlykey** [comment]
The OnlyKey app is only capable of entering PIN for the OnlyKey DUO. This tradeoff is because the device keypad on the DUO is small. The full size OnlyKey requires entering PIN on device, this way there is no chance of software capturing a user's PIN.

**Comment by mihakrumpestar** [comment]
Sorry for not being clear upfront, I am talking about the OnlyKey DUO.

**Comment by onlykey** [comment]
It would be possible to do with the OnlyKey CLI, we may be able to get this in the next release, if you would like to give it a try we do accept PRs.

**Comment by mihakrumpestar** [comment]
Thank you for the clarification. If I find the time, will give it a try.
