### ISSUE TITLE
Setting delay without Tab/Return selected causes wrong Google Auth output

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-Firmware#23]
Steps to reproduce:
1. Set PINs
2. Configure a slot for example with a username= 'test' and set a delay of '2', then set a Google Auth = '6eehbbzafppudotowgnfagakovdecdmu'
3. Click Submit
4. Open text editor, press button of configured slot and notice output of google auth code does not match correct code. Use '6eehbbzafppudotowgnfagakovdecdmu' in http://blog.tinisles.com/2011/10/google-authenticator-one-time-password-algorithm-in-javascript/

**Comment by onlykey** [comment]
@jaroszke I am pretty sure this is no longer an issue if you want to double check we can close this out.

**Comment by onlykey** [comment]
Have not seen this issue
