### ISSUE TITLE
Flexible string or character between PW and 2FA

### ISSUE THREAD

**Issue by alaska** [trustcrypto/OnlyKey-Firmware#36]
Some 2FA solutions prefer a character between the username and password.  It would be nice if we could customize this so that instead of tab or return, we were also presented with the option to send a string before 2FA.

**Comment by onlykey** [comment]
Hmm I have not seen anything like this. Can you provide a link so I can check it out?

**Comment by alaska** [comment]
Ah, I just discovered you can simply leave the 2FA radio buttons for tab and return blank.  This means you can just add the separator to the end of your password and it will work just fine :)
