### ISSUE TITLE
Label wipe when setting 6a

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-Firmware#41]
1.  Set Label on slot 1a &1b

2. Set label on slot 6a

3. Notice that the label on slot 1b is now empty

[overwritinglabelserialmonitor.txt](https://github.com/trustcrypto/OnlyKey-Firmware/files/700535/overwritinglabelserialmonitor.txt)

[overwritinglabelappconsole.log.zip](https://github.com/trustcrypto/OnlyKey-Firmware/files/700537/overwritinglabelappconsole.log.zip)

**Comment by jaroszke** [comment]
It also alters the user name messes up the URL, Username and password values

**Comment by jaroszke** [comment]
It also messes up the URL, Username and Password values that were set.

**Comment by onlykey** [comment]
fixed
