### ISSUE TITLE
Issue 41 still present

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-Firmware#44]
[randomslotlabelgetswiped-app.txt](https://github.com/trustcrypto/OnlyKey-Firmware/files/773054/randomslotlabelgetswiped-app.txt)

After setting all slots, one label will get wiped and then resetting that label causes another label to get wiped.

[anotherlabelgets wiped.txt](https://github.com/trustcrypto/OnlyKey-Firmware/files/773052/anotherlabelgets.wiped.txt)

**Comment by onlykey** [comment]
@jaroszke fixed
