### ISSUE TITLE
Backup-firmware: Google Auth not outputting correct code

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-Firmware#45]
Backup file attached, after restore try to set a slot with google auth using gmail.
Secret key
qpnr ya6x lit7 f2dd ybkj k6qs osb7 5sbw

[onlykey-backup-1487211569934.txt](https://github.com/trustcrypto/OnlyKey-Firmware/files/788736/onlykey-backup-1487211569934.txt)

**Comment by onlykey** [comment]
@jaroszke found the issue pushing fix. Good find
