### ISSUE TITLE
Onlykey not outputting correct Yubikey

### ISSUE THREAD

**Issue by PyRoAcIdK** [trustcrypto/OnlyKey-Firmware#46]
Hi Team,

My Yubikey has been setup twice, however I have the same problem.
I can see the new public key, registered and checked with the original Yubikey, it validates successfully.

I have programmed the OnlyKey, the public part of the key is correct, however, when I generate code, it unsuccessfully validates.

Can you please provide any advice?

Thank you

**Comment by onlykey** [comment]
@PyRoAcIdK Do you have the same key loaded on both your Yubikey and OnlyKey? If so this is the issue Yubikey is counter based, if you have the same key on two devices one of them will have an out of sync counter.
