### ISSUE TITLE
Wiping Yubikey values corrupts all slots

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-Firmware#47]
[onlykey-backup-1487211569934.txt](https://github.com/trustcrypto/OnlyKey-Firmware/files/823214/onlykey-backup-1487211569934.txt)

Load the backup above:
After restore

1. Unlock OK 7 x 1 is the pin
2. Open notepad and press slot 1a, note the output.
3. In the app under Add YubiKey Security Info, select wipe from OnlyKey.
4. Press 1a, notice OK output and locks up. 

Happens on both OK and OK Color

**Comment by onlykey** [comment]
found the issue and fixed @jaroszke
