### ISSUE TITLE
Request: Link to firmware update instructions in release notes

### ISSUE THREAD

**Issue by M-Pixel** [trustcrypto/OnlyKey-Firmware#71]
The release notes do not appear to contain instructions on how to apply the firmware update, nor do they contain a link to the documentation that does.

[crp.to](https://crp.to) also lacks firmware update instructions, or a link thereto.

At this moment in time, a Google search for "Onlykey firmware update" does not have a link to the proper documentation on the front page.

(The instructions can be found [here](https://docs.crp.to/usersguide.html#loading-onlykey-firmware))

**Comment by onlykey** [comment]
Added user guide link to release notes. Planning on announcing the release today with more information.
