### ISSUE TITLE
config mode

### ISSUE THREAD

**Issue by ordulfo** [trustcrypto/OnlyKey-Firmware#84]
holding #6  for 5+ seconds does NOT turn onlykey off to then allow me to re-enter code to enter configuration mode. Any suggestions??? Trying to bakup info, but there is no way to do it if I can't enter config mode.
Any help out there?

Thank you

**Comment by onlykey** [comment]
@ordulfo If you have purchased or have loaded the international travel edition firmware that is probably why - https://docs.crp.to/ite.html
