### ISSUE TITLE
Change URLs in OnlyKey_Beta.ino file to reflect HTTPS

### ISSUE THREAD

**Issue by jgreever** [trustcrypto/OnlyKey-Firmware#86]
Being focused on security and all, could we change the URLs in the OnlyKey_Beta.ino file from:

https://github.com/trustcrypto/OnlyKey-Firmware/blob/db889bf016d00b457bc593793892d7648733631f/OnlyKey_Beta/OnlyKey_Beta.ino#L20
https://github.com/trustcrypto/OnlyKey-Firmware/blob/db889bf016d00b457bc593793892d7648733631f/OnlyKey_Beta/OnlyKey_Beta.ino#L35
to:

**`* the OnlyKey Project (https://crp.to/ok)"`**

since the site supports full https

I understand that this is just a cosmetic change, but I feel it may add to the secure feeling of using the software/hardware/website and easy any worries of weird MITM attacks or other tinfoil hat problems.

Thank you very much!

**Comment by onlykey** [comment]
This has been changed. The site is HTTPS only but changing the link in the license isn't an issue.
