### ISSUE TITLE
U2F not restored between beta 6 and 7

### ISSUE THREAD

**Issue by M-Pixel** [trustcrypto/OnlyKey-Firmware#87]
I just upgraded from beta 6 to beta 7.  Now I get errors when logging into sites that I had previously registered FIDO U2F with.  Everything else appears to have been properly restored.  Is this to be expected?  If so, it should be loudly announced in all corresponding documentation.  I recall reading about this being an issue upgrading from 5 to 6, but I thought it was supposed to have been fixed in 6.

**Comment by onlykey** [comment]
@M-Pixel I believe this was mentioned in the release but yes it should probably be louder announcement. The next release will also require re-registering U2F as we are moving to FIDO2.
