### ISSUE TITLE
[ and ] incorrectly mapped for French Belgium

### ISSUE THREAD

**Issue by tdeleeuw** [trustcrypto/OnlyKey-Firmware#93]
based on picture ![image](https://user-images.githubusercontent.com/14175340/67374844-12b64700-f582-11e9-8399-56b98906a63f.png) the [ and ] keys are swapped in keylayouts.c.

```
//Line 3954
ASCII_5B=KEY_RIGHT_BRACE + ALTGR_MASK;// 91 [ --> Should be KEY_LEFT_BRACE
ASCII_5C=KEY_NON_US_100 + ALTGR_MASK;// 92
ASCII_5D=KEY_LEFT_BRACE + ALTGR_MASK;// 93 ] --> Should be KEY_RIGHT_BRACE
```
Tested with firmware 0.2-beta8c, when you enter [ in the app and use the password, it types ] and vice-versa.

**Comment by onlykey** [comment]
@tdeleeuw Thanks we will get this fix in the next release
